### ISSUE TITLE
Add benchmark module and setup Baseline Profile generator

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2023#719]
**Idea Description**

If we add the benchmark module, we can introduce the baseline profile.
The goal is to add a benchmark module and set up baseline profile generator.

**Reference images and links**
- https://developer.android.com/topic/performance/baselineprofiles/create-baselineprofile

**Comment by l2hyunwoo** [comment]
🙋‍♂️

**Comment by momomomo111** [comment]
@l2hyunwoo Thanks! Assigned!

**Comment by takahirom** [comment]
@l2hyunwoo  I hope all is going well. Would you have some time to update me on how this issue is progressing?

**Comment by l2hyunwoo** [comment]
@takahirom Hello, I've already done, but some error delays to complete this issue.

I made baselineprofile module and make success to make baseline-prof.txt when variant is dev. But in case that variant is prod, it occurs error with below message.

```
Exception thrown during onBeforeAll invocation of plugin com.android.tools.utp.plugins.host.apkinstaller.AndroidTestApkInstallerPlugin.
Failed to install APK: [/Users/hyunwoo/StudioProjects/conference-app-2023/baselineprofile/build/outputs/apk/prod/nonMinifiedRelease/baselineprofile-prod-nonMinifiedRelease.apk] on device emulator-5554.
com.google.testing.platform.core.error.UtpException: ErrorName: Test APK installation Error
NameSpace: AndroidTestApkInstallerPlugin
ErrorCode: 2002
ErrorType: TEST
Message: Failed to install APK: [/Users/hyunwoo/StudioProjects/conference-app-2023/baselineprofile/build/outputs/apk/prod/nonMinifiedRelease/baselineprofile-prod-nonMinifiedRelease.apk] on device emulator-5554.
	at com.android.tools.utp.plugins.host.apkinstaller.AndroidTestApkInstallerPlugin.beforeAll(AndroidTestApkInstallerPlugin.kt:206)
	at com.google.testing.platform.plugin.PluginLifecycle$onBeforeAll$1$2$1$1.invoke(PluginLifecycle.kt:163)
	at com.google.testing.platform.plugin.PluginLifecycle$onBeforeAll$1$2$1$1.invoke(PluginLifecycle.kt:163)
	at com.google.testing.platform.plugin.PluginLifecycle$verify$1.invoke(PluginLifecycle.kt:104)
	at com.google.testing.platform.api.event.Events.verify(Events.kt:31)
	at com.google.testing.platform.plugin.PluginLifecycle.verify(PluginLifecycle.kt:104)
	at com.google.testing.platform.plugin.PluginLifecycle.access$verify(PluginLifecycle.kt:52)
	at com.google.testing.platform.plugin.PluginLifecycle$onBeforeAll$1$2$1.invoke(PluginLifecycle.kt:163)
	at com.google.testing.platform.plugin.PluginLifecycle$onBeforeAll$1$2$1.invoke(PluginLifecycle.kt:162)
	at com.google.testing.platform.plugin.PluginLifecycleKt$invokeOrThrow$1.invoke(PluginLifecycle.kt:374)
	at com.google.testing.platform.plugin.PluginLifecycleKt$invokeOrThrow$1.invoke(PluginLifecycle.kt:374)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
```

If you are okay, can you support to find reason of this error? I'll make draft pull request, then test with your local environment with prod variant.

**Comment by ravenfeld** [comment]
> @takahirom Hello, I've already done, but some error delays to complete this issue.
> 
> I made baselineprofile module and make success to make baseline-prof.txt when variant is dev. But in case that variant is prod, it occurs error with below message.

Hello, I have the same problem. How did you fix it?

**Comment by Subuday** [comment]
Experience the same problem.

**Comment by dijkstraz** [comment]
I was facing the same issue.  
I had created 2 modules one for benchmark and another for baseline profile. 

I had moved all profile generators from baseline module to benchmark module and they work perfectly fine.

**Comment by mahmood199** [comment]
I was facing the same issue.  
I had created 2 modules one for benchmark and another for baseline profile. 

I had moved all profile generators from baseline module to benchmark module and they work perfectly fine.
