### ISSUE TITLE
Fix R8 rule

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#988]
**Idea Description**
I was preparing the release build and the build succeeded, but the app subsequently crashed.

I think you can see the error by using `isMinifyEnabled = true`.
It is ok to disable r8 full mode. Because it is better than not working.

```
2023-08-27 18:33:36.115 24759-24759 AndroidRuntime          pid-24759                            E  FATAL EXCEPTION: main
                                                                                                    Process: io.github.droidkaigi.confsched2023, PID: 24759
                                                                                                    k0.j: Compose Runtime internal error. Unexpected or incorrect use of the Compose internal runtime API (pending composition has not been applied). Please report to Google or use https://goo.gle/compose-feedback
                                                                                                    	at y5.g.x(SourceFile:16)
                                                                                                    	at k0.d0.q(SourceFile:1)
                                                                                                    	at k0.d0.p(SourceFile:4)
                                                                                                    	at k0.k2.a(SourceFile:31)
                                                                                                    	at k0.m.a(SourceFile:10)
                                                                                                    	at k0.d0.j(SourceFile:1)
                                                                                                    	at n1.f0.c(SourceFile:102)
                                                                                                    	at n1.a0.g0(SourceFile:140)
                                                                                                    	at androidx.compose.material3.q3.invoke(SourceFile:578)
                                                                                                    	at n1.k0.f(SourceFile:33)
                                                                                                    	at n1.b0.f(SourceFile:9)
                                                                                                    	at r.s0.a(SourceFile:242)
                                                                                                    	at r.s0.n(SourceFile:171)
                                                                                                    	at e0.i0.d(SourceFile:64)
                                                                                                    	at t0.x.a(SourceFile:62)
                                                                                                    	at p1.k1.a(SourceFile:76)
                                                                                                    	at p1.j0.r(SourceFile:140)
                                                                                                    	at p1.j0.m0(SourceFile:120)
                                                                                                    	at p1.s.W(SourceFile:18)
                                                                                                    	at n1.v0.c(SourceFile:31)
                                                                                                    	at p1.i0.n(SourceFile:15)
                                                                                                    	at e0.i0.d(SourceFile:64)
                                                                                                    	at t0.x.a(SourceFile:62)
                                                                                                    	at p1.k1.a(SourceFile:76)
                                                                                                    	at p1.j0.n0(SourceFile:98)
                                                                                                    	at p1.d0.K(SourceFile:30)
                                                                                                    	at p1.o0.j(SourceFile:223)
                                                                                                    	at p1.o0.f(SourceFile:129)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.t(SourceFile:62)
                                                                                                    	at p1.g1.a(SourceFile:4)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:19)
                                                                                                    	at android.view.View.draw(View.java:22707)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21579)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21535)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21535)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21535)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21535)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4525)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4245)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8787)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:780)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Reference images and links**

**Comment by Corvus400** [comment]
It looks difficult but I would like to try.🙋

**Comment by takahirom** [comment]
@Corvus400 Thanks for stepping up to tackle this challenging PR!
